# Generated by Django 5.0.4 on 2024-12-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DMRData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(max_length=50)),
                ('event', models.CharField(max_length=100)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('channel_number', models.IntegerField(blank=True, null=True)),
                ('frequency', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('timeslot', models.CharField(blank=True, max_length=10, null=True)),
                ('details', models.TextField()),
                ('event_id', models.BigIntegerField()),
            ],
        ),
    ]
