# Generated by Django 5.0.4 on 2024-12-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdrtrunk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmrdata',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
