# Generated by Django 5.0.4 on 2024-12-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdrtrunk', '0002_alter_dmrdata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmrdata',
            name='event_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
