# Generated by Django 5.0.4 on 2024-12-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdrtrunk', '0003_alter_dmrdata_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmrdata',
            name='color_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
