# Generated by Django 5.0.4 on 2024-12-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdrtrunk', '0004_dmrdata_color_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dmrdata',
            options={'verbose_name': 'DMR Data', 'verbose_name_plural': 'DMR Data'},
        ),
    ]
