# Generated by Django 5.0.4 on 2024-12-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdrtrunk', '0005_alter_dmrdata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmrdata',
            name='frequency',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
