# Generated by Django 5.0.4 on 2025-01-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdrtrunk', '0006_alter_dmrdata_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmrdata',
            name='duration_ms',
        ),
        migrations.AddField(
            model_name='dmrdata',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
