# Generated by Django 5.0.4 on 2025-01-31 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdrtrunk', '0007_remove_dmrdata_duration_ms_dmrdata_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dmrdata',
            old_name='duration',
            new_name='duration_s',
        ),
    ]
