# Generated by Django 5.0.4 on 2025-02-05 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdrtrunk', '0008_rename_duration_dmrdata_duration_s'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('dmr_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gps_data', to='sdrtrunk.dmrdata')),
            ],
            options={
                'verbose_name': 'GPS Data',
                'verbose_name_plural': 'GPS Data',
            },
        ),
    ]
